<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>NuclearOptionChinese</AssemblyName>
    <Product>Nuclear Option Chinese Translation</Product>
    <Version>1.0.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <RootNamespace>NuclearOptionChinese</RootNamespace>
    <GameDir>E:\SteamLibrary\steamapps\common\Nuclear Option</GameDir>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="UnityEngine">
      <HintPath>$(GameDir)\NuclearOption_Data\Managed\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GameDir)\NuclearOption_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(GameDir)\NuclearOption_Data\Managed\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>$(GameDir)\NuclearOption_Data\Managed\UnityEngine.AssetBundleModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(GameDir)\NuclearOption_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(GameDir)\NuclearOption_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(GameDir)\NuclearOption_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(GameDir)\NuclearOption_Data\Managed\Unity.TextMeshPro.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(GameDir)\NuclearOption_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  
  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <ItemGroup>
      <AllOutputFiles Include="$(TargetDir)*.dll" />
    </ItemGroup>
    <Copy SourceFiles="@(AllOutputFiles)" DestinationFolder="$(GameDir)\BepInEx\plugins\NuclearOptionChinese" />
    
    <!-- 只有当目标文件夹没有 translation.json 时才进行复制，防止覆盖用户的翻译进度 -->
    <Copy SourceFiles="NuclearOptionChinese\translation.json" 
          DestinationFolder="$(GameDir)\BepInEx\plugins\NuclearOptionChinese" 
          Condition="!Exists('$(GameDir)\BepInEx\plugins\NuclearOptionChinese\translation.json')" />
    
    <!-- 自动复制字体文件 -->
    <Copy SourceFiles="NuclearOptionChinese\font.ttf" DestinationFolder="$(GameDir)\BepInEx\plugins\NuclearOptionChinese" Condition="Exists('NuclearOptionChinese\font.ttf') AND !Exists('$(GameDir)\BepInEx\plugins\NuclearOptionChinese\font.ttf')" />
    <Copy SourceFiles="NuclearOptionChinese\chinesefont.assets" DestinationFolder="$(GameDir)\BepInEx\plugins\NuclearOptionChinese" Condition="Exists('NuclearOptionChinese\chinesefont.assets') AND !Exists('$(GameDir)\BepInEx\plugins\NuclearOptionChinese\chinesefont.assets')" />
  </Target>
</Project>
